language: node_js
os:
  - linux
  - osx
node_js:
  - "6"
  - "7"
install:
  - npm install
  - npm run tsc
script:
  - npm test
  - npm run tslint
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install g++-4.8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX=gcc-4.9 ; fi
