install:
  - ps: Install-Product node 7.4.0 x64

build_script:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - set prebuild_upload=3627f77733decdea6e1dd938b82a485221678ef0
  - npm run prebuild
  - npm run prebuild-ia32
