environment:
  matrix:
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"

platform:
  - x86
  - x64

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform

build_script:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - npm run prebuild
