parameters:
  arch: 'x64'

steps:
- task: UseNode@1
  inputs:
    version: '22.x'
  displayName: 'Install Node.js 22.x'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: 'Use latest Python 3.x'

- bash: |
    if [ "$(uname)" = "Linux" ]; then
      sudo apt-get update -qq
      if [ "${{ parameters.arch }}" = "arm64" ]; then
        sudo apt-get install -y gcc-10-aarch64-linux-gnu g++-10-aarch64-linux-gnu
        echo "##vso[task.setvariable variable=CC]aarch64-linux-gnu-gcc-10"
        echo "##vso[task.setvariable variable=CXX]aarch64-linux-gnu-g++-10"
      else
        sudo apt-get install -y gcc-10 g++-10
        echo "##vso[task.setvariable variable=CC]gcc-10"
        echo "##vso[task.setvariable variable=CXX]g++-10"
      fi
      SYSROOT_PATH=$(node scripts/linux/install-sysroot.js ${{ parameters.arch }} | grep "SYSROOT_PATH=" | cut -d= -f2)
      echo "##vso[task.setvariable variable=SYSROOT_PATH]$SYSROOT_PATH"
      echo "Sysroot path set to: $SYSROOT_PATH"
    elif [ "$(uname)" = "Darwin" ]; then
      echo "##vso[task.setvariable variable=CC]clang"
      echo "##vso[task.setvariable variable=CXX]clang++"
    fi
  displayName: 'Configure compiler'

- script: npm ci
  displayName: 'Install dependencies'
  env:
    ARCH: ${{ parameters.arch }}
    npm_config_arch: ${{ parameters.arch }}
    SYSROOT_PATH: $(SYSROOT_PATH)
    CC: $(CC)
    CXX: $(CXX)
