trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool: 1es-windows-2022-x64
      tsa:
        enabled: true
    stages:
      - stage: Build
        jobs:
          - job: windows-x64
            pool:
              name: 1es-windows-2022-x64
              os: windows
            templateContext:
              outputs:
                - output: pipelineArtifact
                  targetPath: $(Build.SourcesDirectory)/build/Release
                  artifactName: 'win32-x64'
            steps:
            - template: pipelines/build.yml@self
              parameters:
                arch: x64
          - job: windows-arm64
            pool:
              name: 1es-windows-2022-x64
              os: windows
            templateContext:
              outputs:
                - output: pipelineArtifact
                  targetPath: $(Build.SourcesDirectory)/build/Release
                  artifactName: 'win32-arm64'
            steps:
            - template: pipelines/build.yml@self
              parameters:
                arch: arm64
          - job: macOS-x64
            pool:
              name: Azure Pipelines
              vmImage: macOS-latest
              os: macOS
            templateContext:
              outputs:
                - output: pipelineArtifact
                  targetPath: $(Build.SourcesDirectory)/build/Release
                  artifactName: 'macOS-x64'
            steps:
            - template: pipelines/build.yml@self
              parameters:
                arch: x64
          - job: macOS-arm64
            pool:
              name: Azure Pipelines
              vmImage: macOS-latest
              os: macOS
            templateContext:
              outputs:
                - output: pipelineArtifact
                  targetPath: $(Build.SourcesDirectory)/build/Release
                  artifactName: 'macOS-arm64'
            steps:
            - template: pipelines/build.yml@self
              parameters:
                arch: arm64
          - job: linux-x64
            pool:
              name: 1es-ubuntu-22.04-x64
              os: linux
            templateContext:
              outputs:
                - output: pipelineArtifact
                  targetPath: $(Build.SourcesDirectory)/build/Release
                  artifactName: 'linux-x64'
            steps:
            - template: pipelines/build.yml@self
              parameters:
                arch: x64
          - job: linux-arm64
            pool:
              name: 1es-mariner-2.0-arm64
              os: linux
            templateContext:
              outputs:
                - output: pipelineArtifact
                  targetPath: $(Build.SourcesDirectory)/build/Release
                  artifactName: 'linux-arm64'
            steps:
            - template: pipelines/build.yml@self
              parameters:
                arch: arm64
